name: CI

env:
  VERSION_GO: '1.22'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build & Test"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.VERSION_GO }}

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      
      - name: Kubernetes Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Run unit tests
        run: make
